resources:
  - name: app
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: lawrencef-jfrog/pipeline-test
      branches:
        include: master

pipelines:
  - name: barebones_pipeline
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: app
      execution:
        onExecute:
          - printenv
 
    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - printenv
 
    - name: step_3
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - printenv
 
    - name: step_4
      type: Bash
      configuration:
        inputSteps:
          - name: step_2
          - name: step_3
      execution:
        onExecute:
          - printenv


